### ISSUE TITLE
Switch to quaternion mode

### ISSUE THREAD

**Issue by ycczchina** [mikehoyer/UM7-Arduino#1]
Hi Mike,

From the data sheet, I found that changing value of 0x08 can switch it to quaternion mode. Can you give me some hints to do that?

Thanks,
Zheng

**Comment by mikehoyer** [comment]
Yup, so you have to setup your UM7 to output Quaternion values.  You can do this with the programming tool created by Caleb.  The parser I wrote only works with ASCII characters, so make sure your output from the UM7 is set to ASCII, not binary.

You'll have to add a new case to

```
void UM7::save(){
	switch(address){
	case DREG_EULER_PHI_THETA :		// data[6] and data[7] are unused.
		if(packet_is_batch){
			roll = data[0] << 8;
			roll |= data[1];
			pitch = data[2] << 8;
			pitch |= data[3];
			yaw = data[4] << 8;
			yaw |= data[5];
			roll_rate = data[8] << 8;
			roll_rate |= data[9];
			pitch_rate = data[10] << 8;
			pitch_rate |= data[11];
			yaw_rate = data[12] << 8;
			yaw_rate |= data[13];
		}else{
			roll = data[0] << 8;
			roll |= data[1];
			pitch = data[2] << 8;
			pitch |= data[3];
		}
		break;
	}
}
```

Reference the user manual to see which parameters correspond to which data fields.  Hope that helps.

**Comment by ycczchina** [comment]
```
case DREG_QUAT_AB :
		if(packet_is_batch){
			QW = data[0] << 8;
			QW |= data[1];
			QX = data[2] << 8;
			QX |= data[3];
			QY = data[4] << 8;
			QY |= data[5];
			QZ = data[6] << 8;
			QZ |= data[7];
		}else{
			QW = data[0] << 8;
			QW |= data[1];
			QX = data[2] << 8;
			QX |= data[3];
		}
		break;
```

I already finished this part. Can you tell me how to send commands to due? I wrote something like this:
```
byte tx_data[20];
  tx_data[0] = 's';
  tx_data[1] = 'n';
  tx_data[2] = 'p';
  tx_data[3] = 0x80;// Packet Type byte
  tx_data[4] = 0x08;// Address of GET_FW_REVISION register
  tx_data[5] = 0x03;// Data
  tx_data[6] = ('s' + 'n' + 'p' + 0x80 + 0x08 + 0x03) >>8;// Checksum high byte
  tx_data[7] = ('s' + 'n' + 'p' + 0x80 + 0x08 + 0x03) & 0x0F;// Checksum low byte
  for(int i = 0; i < 7; i++){
    Serial2.write(tx_data[i]);
  }
```

**Comment by mikehoyer** [comment]
The UM7 sends commands to the DUE, and my code parses commands.  I'm not sure what you're doing.

**Comment by ycczchina** [comment]
I want to get quaternions from UM7.
And page 56 of manual is about how to switch to quaternion mode.
Page 36 is about how to send command.

**Comment by mikehoyer** [comment]
Yes, you can do that.  My code is just a parser of the UM7.  RX only.

You can use the CHRobotics Serial Interface to put the UM7 into quaternion mode.

http://www.chrobotics.com/serial-interface

That's what I've done in the past.  Once the UM7 is configured, there really isn't much reason to change what data it puts out.
